{{- $global := . -}}
{{- range $svc := .Values.meshAdapter }}
{{- $key := include "octo-mesh.adapterFullname" (dict "global" $global "svc" $svc) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "octo-mesh.adapterFullname" (dict "global" $global "svc" $svc)  }}
  labels:
    {{- include "octo-mesh.service-labels" (dict "global" $global "name" $key "svc" $svc)   | nindent 4 }}
spec:
  replicas: {{ $svc.replicaCount }}
  selector:
    matchLabels:
      {{- include "octo-mesh.service-selectorLabels" (dict "global" $global "name" $key "svc" $svc) | nindent 6 }}
  template:
    metadata:
      {{- with $svc.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "octo-mesh.service-labels" (dict "global" $global "name" $key "svc" $svc) | nindent 8 }}
        {{- with $svc.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $global.Values.imageDefaults.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: mesh-adapter
        image: "{{ $svc.image.repository }}:{{ $svc.image.tag | default $global.Chart.AppVersion }}"
        imagePullPolicy: {{ $global.Values.imageDefaults.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ $svc.pod.port }}
            protocol: TCP
        env:
          {{- include "octo-mesh.env" (dict "global" $global "name" "meshAdapter" "svc" $svc) | nindent 8 }}
        {{- with $svc.pod.livenessProbe}}            
        livenessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with $svc.pod.readinessProbe}}
        readinessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with $svc.pod.resources}}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- if or $svc.pod.volumeMounts $global.Values.secrets.rootCa }}
        volumeMounts:
        {{- end }}        
        {{- with $svc.pod.volumeMounts }}
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- if $global.Values.secrets.rootCa }}
        - name: root-ca-volume
          mountPath: /etc/ssl/certs/root-ca.pem
          subPath: root-ca.pem
        {{- end }}        
      {{- if or $svc.pod.volumes $global.Values.secrets.rootCa }}
      volumes:
      {{- end }}
      {{- with $svc.pod.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $global.Values.secrets.rootCa }}
      - name: root-ca-volume
        secret:
          secretName: {{ printf "%s-ca" (include "octo-mesh.fullname" $global) }}
      {{- end }}      
      {{- with $svc.pod.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $svc.pod.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $svc.pod.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---      
{{- end }}
