{{- include "checkMandatoryValue" (dict "name" "service-hooks.caKey" "value" .Values.serviceHooks.caKey) }}
{{- include "checkMandatoryValue" (dict "name" "service-hooks.caCrt" "value" .Values.serviceHooks.caCrt) }}
{{- include "checkMandatoryValue" (dict "name" "service-hooks.svcKey" "value" .Values.serviceHooks.svcKey) }}
{{- include "checkMandatoryValue" (dict "name" "service-hooks.svcCrt" "value" .Values.serviceHooks.svcCrt) }}
    
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-webhook-ca" (include "octoMeshCommunicationOperator.fullname" .) }}
  labels:
    {{- include "octoMeshCommunicationOperator.labels" . | nindent 4 }}
type: Opaque
data:
  ca-key.pem: {{ .Values.serviceHooks.caKey | b64enc | quote }}
  ca.pem: {{ .Values.serviceHooks.caCrt | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-webhook-cert" (include "octoMeshCommunicationOperator.fullname" .) }}
  labels:
    {{- include "octoMeshCommunicationOperator.labels" . | nindent 4 }}
type: Opaque
data:
  ca-key.pem: {{ .Values.serviceHooks.svcKey | b64enc | quote }}
  ca.pem: {{ .Values.serviceHooks.svcCrt | b64enc | quote }}
---