{{- include "checkMandatoryValue" (dict "name" "services.identity.signingKey.password" "value" .Values.services.identity.signingKey.password) }}
{{- include "checkMandatoryValue" (dict "name" "secrets.databaseUser" "value" .Values.secrets.databaseUser) }}
{{- include "checkMandatoryValue" (dict "name" "secrets.databaseAdmin" "value" .Values.secrets.databaseAdmin) }}
{{- include "checkMandatoryValue" (dict "name" "secrets.rabbitmq" "value" .Values.secrets.rabbitmq) }}
{{- include "checkMandatoryValue" (dict "name" "services.identity.signingKey.key" "value" .Values.services.identity.signingKey.key) }}
{{- include "checkMandatoryValue" (dict "name" "secrets.crate" "value" .Values.secrets.crate) }}
    
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-backend" (include "octo-mesh.fullname" .) }}
  labels:
    {{- include "octo-mesh.labels" . | nindent 4 }}  
type: Opaque
data:
  identityKeyFile: {{ .Values.services.identity.signingKey.password | b64enc | quote }}
  databaseUser: {{ .Values.secrets.databaseUser | b64enc | quote }}
  databaseAdmin: {{ .Values.secrets.databaseAdmin | b64enc | quote }}
  crate: {{ .Values.secrets.crate | b64enc | quote }}
{{- if .Values.secrets.crate }}  
  crate: {{ .Values.secrets.crate | b64enc | quote }}
{{- end }}
{{- if .Values.notifications.smtp.password }}
  email: {{ .Values.notifications.smtp.password | b64enc | quote }}
{{- end }}
  rabbitmq: {{ .Values.secrets.rabbitmq | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-signing-key" (include "octo-mesh.fullname" .) }}
  labels:
    {{- include "octo-mesh.labels" . | nindent 4 }}  
type: Opaque
data:
  IdentityServer4Auth.pfx: {{ .Values.services.identity.signingKey.key | b64enc | quote }}
---
{{- if .Values.secrets.rootCa }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-ca" (include "octo-mesh.fullname" .) }}
  labels:
    {{- include "octo-mesh.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "checkMandatoryValue" (dict "name" "secrets.rootCa" "value" .Values.secrets.rootCa) }}
  root-ca.pem: {{ .Values.secrets.rootCa | b64enc | quote }}
{{- end }}