apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ printf "%s-mutators" (include "octoMeshCommunicationOperator.fullname" .) }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ .Values.serviceHooks.caCrt | b64enc | quote }}
    service:
      name: {{ include "octoMeshCommunicationOperator.fullname" . }}
      path: /mutate/v1communicationpoolentity
      namespace: {{ .Release.Namespace }}      
  matchPolicy: Exact
  name: mutate.communicationpool.octo-mesh.meshmakers.io.v1alpha1
  rules:
  - apiGroups:
    - octo-mesh.meshmakers.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - communicationpools
  sideEffects: None