apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-operator-operator-role" (include "octoMeshCommunicationOperator.fullname" .) }}
rules:
- apiGroups:
  - octo-mesh.meshmakers.io
  resources:
  - communicationpools
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - create
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
- apiGroups:
  - octo-mesh.meshmakers.io
  resources:
  - communicationpools/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
  - update
  - patch