{{- include "checkMandatoryValue" (dict "name" "serviceHooks.caKey" "value" .Values.serviceHooks.caKey) }}
{{- include "checkMandatoryValue" (dict "name" "serviceHooks.caCrt" "value" .Values.serviceHooks.caCrt) }}
{{- include "checkMandatoryValue" (dict "name" "serviceHooks.svcKey" "value" .Values.serviceHooks.svcKey) }}
{{- include "checkMandatoryValue" (dict "name" "serviceHooks.svcCrt" "value" .Values.serviceHooks.svcCrt) }}
    
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-webhook-ca" (include "octoMeshCommunicationOperator.fullname" .) }}
  labels:
    {{- include "octoMeshCommunicationOperator.labels" . | nindent 4 }}
type: Opaque
data:
  ca-key.pem: {{ .Values.serviceHooks.caKey | b64enc | quote }}
  ca.pem: {{ .Values.serviceHooks.caCrt | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-webhook-cert" (include "octoMeshCommunicationOperator.fullname" .) }}
  labels:
    {{- include "octoMeshCommunicationOperator.labels" . | nindent 4 }}
type: Opaque
data:
  svc-key.pem: {{ .Values.serviceHooks.svcKey | b64enc | quote }}
  svc.pem: {{ .Values.serviceHooks.svcCrt | b64enc | quote }}
---
{{- if .Values.secrets.rootCa }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-ca" (include "octoMeshCommunicationOperator.fullname" .) }}
  labels:
    {{- include "octoMeshCommunicationOperator.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "checkMandatoryValue" (dict "name" "secrets.rootCa" "value" .Values.secrets.rootCa) }}
  root-ca.pem: {{ .Values.secrets.rootCa | b64enc | quote }}
{{- end }}