apiVersion: v1
kind: Service
metadata:
  name: {{ include "octoMeshCommunicationOperator.fullname" . }}
  labels:
    {{- include "octoMeshCommunicationOperator.labels" . | nindent 4 }}  
spec:
  type: {{ .Values.service.type }}  
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    {{- include "octoMeshCommunicationOperator.selectorLabels" . | nindent 4 }}